import 'package:freezed_annotation/freezed_annotation.dart';

part 'chat_model.freezed.dart';
part 'chat_model.g.dart';

@freezed
class ChatModel with _$ChatModel {
  const factory ChatModel({
    @Default('') String id,
    @Default('') String title,
    @Default('private') String visibility,
    @Default('chat') String section,
    @Default(false) bool isPublishedToDiscover,
    @Default(true) bool isOwner,
    DateTime? createdAt,
    DateTime? updatedAt,
    @Default(0) int messageCount,
    String? lastMessage,
  }) = _ChatModel;

  factory ChatModel.fromJson(Map<String, dynamic> json) =>
      _$ChatModelFromJson(json);
}

/// API returns `content` as a string + optional `metadata.modelName`.
/// We use [content] as the canonical text. [attachments] is for future
/// image/file additions (mobile API doesn't return parts/attachments today).
@freezed
class MessageModel with _$MessageModel {
  const factory MessageModel({
    @Default('') String id,
    @Default('') String chatId,
    @Default('user') String role,
    @Default('') String content,
    String? modelName,
    @Default([]) List<MessageAttachment> attachments,
    DateTime? createdAt,
    /// Client-only flag — true if this is a failed-send placeholder so the
    /// UI can render it as a retry-able failure bubble instead of a real
    /// assistant reply. Server never sends this.
    @Default(false) bool isError,
    /// Client-only — original user text we'd resend on retry. Set on failed
    /// assistant placeholders so the bubble's retry button knows what to send.
    String? retryText,
  }) = _MessageModel;

  factory MessageModel.fromJson(Map<String, dynamic> json) =>
      _$MessageModelFromJson(json);

  /// Persisted messages carry the model under `metadata.modelName`; lift it to
  /// the top level so the "generated by <model>" badge shows on history too.
  static Map<String, dynamic> normalize(Map<dynamic, dynamic> raw) {
    final m = Map<String, dynamic>.from(raw);
    final meta = m['metadata'];
    if (m['modelName'] == null && meta is Map && meta['modelName'] != null) {
      m['modelName'] = meta['modelName'];
    }
    return m;
  }
}

@freezed
class MessageAttachment with _$MessageAttachment {
  const factory MessageAttachment({
    @Default('') String url,
    @Default('application/octet-stream') String contentType,
    String? name,
  }) = _MessageAttachment;

  factory MessageAttachment.fromJson(Map<String, dynamic> json) =>
      _$MessageAttachmentFromJson(json);
}

@freezed
class ChatListResponse with _$ChatListResponse {
  const factory ChatListResponse({
    @Default([]) List<ChatModel> chats,
    String? nextCursor,
    @Default(false) bool hasMore,
  }) = _ChatListResponse;

  factory ChatListResponse.fromJson(Map<String, dynamic> json) =>
      _$ChatListResponseFromJson(json);
}

@freezed
class MessagesResponse with _$MessagesResponse {
  const factory MessagesResponse({
    @Default([]) List<MessageModel> messages,
    String? nextCursor,
    @Default(false) bool hasMore,
  }) = _MessagesResponse;

  // Constructs directly: real response is `{messages, hasMore, cursor:{before,
  // after}}`. We surface `cursor.before` (the oldest id on this page) as
  // nextCursor — the id to send back as `before` to load older messages.
  factory MessagesResponse.fromJson(Map<String, dynamic> json) {
    final rawMsgs = json['messages'];
    final messages = <MessageModel>[];
    if (rawMsgs is List) {
      for (final e in rawMsgs) {
        if (e is Map) {
          try {
            messages.add(MessageModel.fromJson(MessageModel.normalize(e)));
          } catch (_) {/* skip malformed row */}
        }
      }
    }
    final cursor = json['cursor'];
    final before = cursor is Map ? cursor['before'] : null;
    return MessagesResponse(
      messages: messages,
      nextCursor:
          before is String ? before : json['nextCursor'] as String?,
      hasMore: json['hasMore'] is bool ? json['hasMore'] as bool : false,
    );
  }
}

@freezed
class StreamEvent with _$StreamEvent {
  const factory StreamEvent.start({
    required String messageId,
    String? model,
    /// "resume" when the stream is a continuation of a truncated turn.
    /// `null` for a normal new turn.
    String? mode,
  }) = StreamEventStart;

  const factory StreamEvent.token({
    required String content,
  }) = StreamEventToken;

  const factory StreamEvent.usage({
    required int inputTokens,
    required int outputTokens,
    required int totalTokens,
  }) = StreamEventUsage;

  /// Server-assigned id of the assistant turn that just finished. Same id
  /// across `start` and `done`. Needed to call `/complete/resume` and to
  /// target the existing bubble during a resume stream-append.
  ///
  /// `finishReason` per OpenAI semantics: "stop" | "length" | "unknown".
  /// `truncated` is the single boolean signal driving the Continue button —
  /// equals `finishReason == 'length'` server-side.
  const factory StreamEvent.done({
    String? messageId,
    String? finishReason,
    @Default(false) bool truncated,
    /// "resume" if this `done` closes a resume stream rather than a fresh turn.
    String? mode,
  }) = StreamEventDone;

  const factory StreamEvent.error({
    required String message,
    String? code,
  }) = StreamEventError;

  /// Informational status events emitted by the backend auto web-search
  /// pipeline. Three variants today:
  ///   - status="web-searching"        + query + reason
  ///   - status="web-searched"         + resultCount + source
  ///   - status="web-search-no-results"
  /// Future status types (deep-thinking, tool-running, ...) flow through
  /// the same StreamEventStatus event — match on `status` not type.
  const factory StreamEvent.status({
    required String status,
    String? query,
    String? reason,
    int? resultCount,
    String? source,
  }) = StreamEventStatus;

  factory StreamEvent.fromJson(Map<String, dynamic> json) {
    // Sahachiel: read every field type-safely. The /complete NDJSON stream can
    // carry a wrong-typed field - the backend confirmed `code` sometimes arrives
    // as a number, not a string. A blanket `as String?` throws on that and kills
    // the parse of the whole event (and, depending on the caller, the stream).
    // `str()` returns null on a non-string instead of throwing; numeric counts
    // are coerced via num. Same defensive approach as the HTTP _envelope fix.
    String? str(String key) {
      final v = json[key];
      return v is String ? v : null;
    }

    final usage = json['usage'];
    int usageInt(String key) =>
        (usage is Map && usage[key] is num) ? (usage[key] as num).toInt() : 0;

    return switch (str('type')) {
      'start' => StreamEvent.start(
          // messageId may be absent on some backend variants — don't blow up
          // the whole stream just because the start event is half-shaped.
          messageId: str('messageId') ?? '',
          model: str('model'),
          mode: str('mode'),
        ),
      'token' => StreamEvent.token(content: str('content') ?? ''),
      'usage' => StreamEvent.usage(
          inputTokens: usageInt('inputTokens'),
          outputTokens: usageInt('outputTokens'),
          totalTokens: usageInt('totalTokens'),
        ),
      'done' => StreamEvent.done(
          messageId: str('messageId'),
          finishReason: str('finishReason'),
          truncated: json['truncated'] is bool ? json['truncated'] as bool : false,
          mode: str('mode'),
        ),
      'status' => StreamEvent.status(
          status: str('status') ?? '',
          query: str('query'),
          reason: str('reason'),
          resultCount:
              json['resultCount'] is num ? (json['resultCount'] as num).toInt() : null,
          source: str('source'),
        ),
      'error' => StreamEvent.error(
          message: str('message') ?? str('error') ?? 'Unknown error',
          code: str('code'),
        ),
      _ => StreamEvent.error(message: 'Unknown event type: ${json['type']}'),
    };
  }
}
